import { FridgeItem } from "@/state/slices/fridgeInventorySlice";

/**
 * Defines the possible UI modes or "intents" that the Assistant can trigger.
 * These strings determine which 3D component is rendered in the AR Scene.
 */
export type InterfaceType =
  | "instruction"
  | "timer"
  | "shopping_list"
  | "warning"
  | "success"
  | "idle"
  | "error"
  | "fridge_inventory"
  | "suggest_recipe"
  | "step_guide";

/**
 * Represents a single ingredient with detailed metadata.
 * Used when breaking down recipe requirements vs. user inventory.
 */
export interface IngredientDetailed {
  /** The name of the ingredient (e.g., "Flour"). */
  name: string;
  /** The numeric quantity required. */
  quantity: number;
  /** The unit of measurement (e.g., "grams", "cups"). */
  unit: string;
  /** Indicates if the user already has this ingredient in their inventory. */
  fromUserIngredients: boolean;
}

/**
 * Represents a single, actionable step within a recipe.
 * Designed to be read aloud or displayed one at a time in AR.
 */
export interface AtomicStep {
  /** Unique identifier for the step. */
  id: string;
  /** The main action verb (e.g., "Chop", "Boil"). */
  actionVerb: string;
  /** The object of the action (e.g., "Onions"). */
  targetObject: string;
  /** Full textual description of the step instructions. */
  details: string;
  /** Optional icon identifier to visualize the action. */
  icon?: string;
  /** Optional duration in seconds if this step involves a timer (e.g., boiling). */
  timerSeconds?: number;
  /** Optional safety warning or tip (e.g., "Hot surface"). */
  warning?: string | null;
}

/**
 * Represents a complete recipe structure generated by the AI.
 */
export interface SingleRecipe {
  /** The name of the recipe. */
  title?: string;
  /** List of ingredients the user already possesses. */
  ingredientsYouHave?: string[];
  /** List of ingredients the user needs to buy. */
  ingredientsMissing?: string[];
  /** Structured list of ingredients with quantities. */
  ingredientsDetailed?: IngredientDetailed[];

  /** Sequential list of steps to complete the recipe. */
  steps?: AtomicStep[];

  /** Total estimated time in minutes. */
  estimatedTimeMinutes?: number;
  /** Difficulty level of the recipe. */
  difficulty?: "easy" | "medium" | "hard";
}

/**
 * Payload for the "suggest_recipe" interface.
 * Contains a list of potential recipes generated based on user input or inventory.
 */
export interface RecipeSuggestionData {
  /** A list of suggested recipes. */
  recipes?: SingleRecipe[];
  /** The title of the currently selected or active recipe suggestion. */
  selectedTitle?: string;
}

/**
 * Standardized response format from the AI Assistant API.
 * This structure routes the frontend to the correct UI state and carries necessary data.
 */
export interface AIResponse {
  /** The type of interface/action to trigger. */
  type: InterfaceType;

  /** Dynamic payload data depending on the interface type. */
  data: {
    /** General text response or instruction. */
    text?: string;
    /** Duration in seconds (for timers). */
    seconds?: number;
    /** Label or name (for timers, shopping items). */
    label?: string;
    /** Unique identifier (for timers). */
    id?: string;

    /** Quantity for shopping list items. */
    quantity?: number;
    /** List of shopping items (for bulk operations). */
    shoppingItems?: Array<{ label: string; quantity?: number | null }>;

    /** List of fridge inventory items. */
    fridgeItems?: FridgeItem[];

    /** The full recipe object (for recipe generation). */
    recipe?: SingleRecipe;

    /** Navigation direction (next, prev, jump). */
    direction?: "next" | "prev" | "jump";
    /** Target step index or keyword for navigation. */
    target?: number | "first" | "last";
  } & RecipeSuggestionData;
}
