import { StateCreator } from "zustand";
import type { RecipeSuggestionData } from "@/types/interfaces";

/**
 * Interface definition for the Recipe Slice.
 * Manages the state related to recipe suggestions generated by the AI
 * and the user's current selection.
 */
export interface RecipeSlice {
  /**
   * The current recipe suggestion data returned by the AI.
   * Contains a list of possible recipes based on user input or available ingredients.
   */
  suggestion: RecipeSuggestionData | null;

  /**
   * The index of the currently selected recipe from the suggestion list.
   * Used to highlight the selection in the UI or preview details.
   */
  selectedSuggestionIndex: number | null;

  /**
   * Updates the current suggestion data.
   * @param data - The new suggestion object or null to clear it.
   */
  setSuggestion: (data: RecipeSuggestionData | null) => void;

  /**
   * Sets the currently selected suggestion index.
   * @param index - The index of the recipe to select.
   */
  setSelectedSuggestionIndex: (index: number | null) => void;
}

/**
 * Slice creator for the Recipe state.
 * Implements the logic for storing and updating AI-generated recipe suggestions.
 *
 * @param set - The Zustand set function.
 */
export const createRecipeSlice: StateCreator<RecipeSlice> = (set) => ({
  suggestion: null,
  selectedSuggestionIndex: null,

  setSuggestion: (data) => set({ suggestion: data }),
  setSelectedSuggestionIndex: (index) =>
    set({ selectedSuggestionIndex: index }),
});
